version: '2.1'
services:
  attendance-service:
    image: ccr.ccs.tencentyun.com/kkkzoz/attendance-service:139.9.245.28
    container_name: attendance-service
    ports:
      - "8004:8004"
      - "7004:7004"

  gateway:
    image: ccr.ccs.tencentyun.com/kkkzoz/gateway:139.9.245.28
    container_name: gateway
    ports:
      - "8800:8800"
      - "7800:7800"

  homework-service:
    image: ccr.ccs.tencentyun.com/kkkzoz/homework-service:139.9.245.28
    container_name: homework-service
    ports:
      - "8001:8001"
      - "7001:7001"

  manage-service:
    image: ccr.ccs.tencentyun.com/kkkzoz/manage-service:139.9.245.28
    container_name: manage-service
    ports:
      - "8003:8003"
      - "7003:7003"

  material-service:
    image: ccr.ccs.tencentyun.com/kkkzoz/material-service:139.9.245.28
    container_name: material-service
    ports:
      - "8006:8006"
      - "7006:7006"

  plan-service:
    image: ccr.ccs.tencentyun.com/kkkzoz/plan-service:139.9.245.28
    container_name: plan-service
    ports:
      - "8005:8005"
      - "7005:7005"

  project-service:
    image: ccr.ccs.tencentyun.com/kkkzoz/project-service:139.9.245.28
    container_name: project-service
    ports:
      - "8002:8002"
      - "7002:7002"


  security-service:
    image: ccr.ccs.tencentyun.com/kkkzoz/security-service:139.9.245.28
    container_name: security-service
    ports:
      - "8000:8000"
      - "7000:7000"

