global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'licensingservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['licensingservice:8080']
  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['configserver:8071']